/**
 * Bug 修复流水线各阶段的 AI Prompt 模板
 * 独立管理，便于调优 prompt 而不改流水线逻辑
 */

/**
 * Phase 1: Understand — 让 AI 分析 issue 内容
 */
export function buildUnderstandPrompt(issue: {
  title: string;
  body: string;
  comments: string[];
}): string {
  return `你是一个经验丰富的软件工程师。请分析以下 GitHub issue，给出结构化的 bug 分析报告。

## Issue 标题
${issue.title}

## Issue 正文
${issue.body}

${issue.comments.length > 0 ? `## Issue 评论\n${issue.comments.join('\n---\n')}` : ''}

请输出以下格式的分析报告：

## Bug 分析报告
- **严重程度**: [critical / major / minor]
- **类型**: [逻辑错误 / 边界条件 / 空指针 / 并发问题 / 环境问题 / 其他]
- **影响范围**: [描述影响的模块/功能]
- **关联文件**: [推测可能需要修改的文件列表]
- **复现步骤**: [1. 2. 3. ...]
- **预期行为**: [正确的行为应该是什么]
- **实际行为**: [当前错误的行为]
- **修复建议**: [初步的修复思路]

如果信息不足以判断，请明确说明缺什么信息。`;
}

/**
 * Phase 2: Reproduce — 让 AI 尝试写复现脚本
 */
export function buildReproducePrompt(analysis: string): string {
  return `根据以下 bug 分析报告，请尝试编写一个复现脚本或单元测试。

${analysis}

## 要求
1. 先查看项目中已有的测试文件，了解测试框架和风格
2. 写一个最小复现脚本/测试，只关注此 bug 的核心逻辑
3. 不需要写完整的集成测试，只要能验证 bug 存在即可
4. 运行这个测试并报告结果

## 输出格式
- **复现结果**: [REPRODUCED / PARTIAL / CANNOT]
- **复现证据**: [测试输出/日志片段]
- **根因定位**: [如果找到根因，描述具体是什么问题]
- **无法复现的原因**: [如果 CANNOT，说明为什么，缺什么环境/信息]`;
}

/**
 * Phase 3: Fix — 让 SpicaAgent 修复 bug
 */
export function buildFixPrompt(issue: {
  title: string;
  body: string;
  number: number;
}, analysis: string, reproEvidence: string): string {
  return `修复以下 bug。你必须使用编辑工具实际修改代码文件。

## Bug #${issue.number}: ${issue.title}
${issue.body}

## 分析
${analysis}

## 复现
${reproEvidence}

## 要求
1. 用 read 工具读取需要修改的文件
2. 用编辑工具修改代码（必须实际执行）
3. 运行 node test.js 确认测试通过
4. 测试全部通过后才算完成

现在开始改代码。`;
}

/**
 * Phase 4: Verify — 验证 prompt（Agent 修复后）
 */
export function buildVerifyPrompt(): string {
  return `运行 node test.js 验证修复。如果输出显示所有测试通过（PASS），回复 VERIFIED。如果任何测试失败，回复 FAILED 并说明原因。`;
}

/**
 * Issue 留言模板 — 开始处理
 */
export function buildStartComment(): string {
  return [
    ':robot: spica-cli auto-issue-handler 正在处理此 issue...',
    '',
    '流水线: Understand → Reproduce → Fix → Verify → PR',
    '',
    '如果处理失败，会在此留言说明原因。',
  ].join('\n');
}

/**
 * Issue 留言模板 — 处理成功
 */
export function buildSuccessComment(prUrl: string, summary: string): string {
  return [
    ':white_check_mark: spica-cli 已完成自动修复。',
    '',
    `### Pull Request: ${prUrl}`,
    '',
    '### 修改摘要',
    summary,
    '',
    ':warning: 此 PR 由 AI 自动生成，请人工 review 后合并。',
  ].join('\n');
}

/**
 * Issue 留言模板 — 处理失败
 */
export function buildFailComment(phase: string, reason: string): string {
  return [
    ':x: spica-cli 自动处理失败。',
    '',
    `### 失败阶段: ${phase}`,
    '',
    '### 失败原因',
    reason,
    '',
    '需要人工介入处理此 issue。管理员将收到邮件通知。',
  ].join('\n');
}

/**
 * Issue 留言模板 — 无法复现
 */
export function buildCannotReproduceComment(attempt: string): string {
  return [
    ':question: spica-cli 无法复现此 bug。',
    '',
    '### 尝试过程',
    attempt,
    '',
    '请提供以下信息以便继续：',
    '- 运行环境（OS、版本、配置）',
    '- 更详细的复现步骤',
    '- 相关的日志/截图',
    '',
    '提供信息后我会重新尝试修复。',
  ].join('\n');
}

/**
 * PR 正文模板
 */
export function buildPRBody(
  issueNumber: number,
  issueUrl: string,
  summary: string,
  testResult: string,
): string {
  return [
    '## Summary',
    `Auto-generated fix for [#${issueNumber}](${issueUrl})`,
    '',
    '## Changes',
    summary,
    '',
    '## Verification',
    testResult,
    '',
    '---',
    ':robot: Generated by [spica-cli](https://github.com/zisonzishen0415-stack/spica-cli) auto-issue-handler',
    ':warning: Do not merge without human review.',
  ].join('\n');
}
